### ISSUE TITLE
Big Sur: audio not working

### ISSUE THREAD

**Issue by SixTni9** [juanlatorre/MSI-PL62-7RC-OC-Hackintosh#1]
Hi juanlatorre, 
I am big fan of your work. I really appreciate the work you did for this laptop. I had lost hope of ever getting hackintosh on this laptop.
Following your work I was able to boot big sur on this laptop.
But due to some reason the default configuration for audio is not working here i.e alcid=4.

can you please share your updated efi on this repo.

please keep this project active and not let it die😭🙏🏻🙏🏻🙏🏻

**Comment by SixTni9** [comment]
Fixed . Alcid=4 worked. Changed audio to default speakers in settings.

**Comment by juanlatorre** [comment]
Wow, thanks for your support bro, unfortunately my laptop died a few weeks ago so I will not be able to update this repo anymore.
